Sign in | All tests
vitali-akulau/react-app pull request #2
Opened 2021-05-14 12:32 UTC by vitali-akulau

- Autotests implementation from Sign In suite
---
![client 2021-05-14 15-30-56](https://user-images.githubusercontent.com/19670029/118271011-6e7c5400-b4c9-11eb-9d9b-c22a13159fcf.png)

2021-05-14 13:24 UTC, s34rching requested changes
I need to explain few concepts of Cypress that you should always remember about

2021-05-14 13:24 UTC, s34rching commented on client/cypress/.eslintrc.json
> +    "no-use-before-define": ["error", { "functions": false, "classes": true }]
nice

2021-05-14 13:24 UTC, s34rching commented on client/cypress/integration/authentication/sign-in.spec.js
> +      .get(HomePage.signOutLink)
I believe this is the only thing which is sufficient to tell that user has been logged in

2021-05-14 13:24 UTC, s34rching commented on client/cypress/integration/authentication/sign-in.spec.js
> +      .and('contain.text', SIGN_IN_LINK_TEXT);
there are too much assertions
please do not forget that something might `not` be on the page
make it more efficient

2021-05-14 13:24 UTC, s34rching commented on client/cypress/model/SignInPage.js
> +          cy.wrap(e).type(value)
what is the reason of wrapping?

2021-05-14 13:24 UTC, s34rching commented on client/cypress/integration/authentication/sign-in.spec.js
> +      .should('be.visible');
oh man
you should not chain methods this way b/c you are disabling Cypress waiting for conditions
we need to hop on the call to let me explain it to you

2021-05-14 13:24 UTC, s34rching commented on client/cypress/integration/authentication/sign-in.spec.js
> +      .should('be.visible');
oh man
you should not chain methods this way b/c you are disabling Cypress waiting for conditions
we need to hop on the call to let me explain it to you

2021-05-14 13:24 UTC, s34rching commented on client/cypress/integration/authentication/sign-in.spec.js
>  describe('Sign in page', () => {
please try to wrap tests into their separate `describe` blocks to distinct `sign-in` from `sign-up` tests

2021-05-14 13:24 UTC, s34rching commented on client/cypress/integration/authentication/sign-in.spec.js
> +const HOME_PAGE_URL_PATH = 'http://127.0.0.1:3000/';
create another helper file which contains all these hard-coded things

2021-05-14 13:24 UTC, s34rching commented on client/cypress/fixtures/user.js
> +  differentConfirmPassword: 12345,
you cannot iterate over your fixture the way you've composed values
my suggestion is to create array containing various `user` objects
then you can provide the data and run them using any of iteration methods

2021-05-14 13:24 UTC, s34rching commented on client/cypress/model/SignInPage.js
> +    return this;
what is the sacred sense of returning `this`?

2021-05-14 13:41 UTC, vitali-akulau commented on client/cypress/integration/authentication/sign-in.spec.js
> +      .get(HomePage.signOutLink)
Agree. Have fixed

2021-05-14 13:50 UTC, vitali-akulau commented on client/cypress/model/SignInPage.js
> +          cy.wrap(e).type(value)
I use test data from user.js. Some keys have empty value. If I try pass empty value in the tests I get an exception.
![client 2021-05-14 16-48-07](https://user-images.githubusercontent.com/19670029/118279834-41816e80-b4d4-11eb-815a-5d3fe96f0e38.png)
The current implementation makes it possible not to pass empty values

2021-05-14 14:09 UTC, vitali-akulau commented on client/cypress/model/SignInPage.js
> +    return this;
Using 'this' get a possibility create a chain calls for one instance only. 
For example:
With 'this'
![react-app – sign-in spec js 2021-05-14 17-02-50](https://user-images.githubusercontent.com/19670029/118281935-6a0a6800-b4d6-11eb-919a-e281c504bb60.png)
Without 'this'
![react-app – sign-in spec js 2021-05-14 17-04-44](https://user-images.githubusercontent.com/19670029/118282019-827a8280-b4d6-11eb-8829-d024bebebb20.png)
Using this, you can chain calls for a single instance, even if the test flow goes through multiple pages.
Technically, it doesn't do anything. But with this approach, you see beautifully designed code

2021-05-17 08:41 UTC, s34rching reviewed
Just comment

2021-05-17 08:41 UTC, s34rching commented on client/cypress/fixtures/helper.js
> +const helper = {
`constants`?

2021-05-17 12:35 UTC, ivankatsenya requested changes
it needs more updates

2021-05-17 12:35 UTC, ivankatsenya commented on client/cypress/fixtures/constants.js
> +const constants = {
looks better

2021-05-17 12:35 UTC, ivankatsenya commented on client/src/components/sign-in/sign-in.component.jsx
> +      <SignInTitle data-test="sign-in-title">I already have an account</SignInTitle>
but do not abuse attributes adding regarding there might not be any or adding attributes will be blocked to you

2021-05-17 12:35 UTC, ivankatsenya commented on client/cypress/integration/authentication/sign-in.spec.js
> +  }
this condition is always truthy, b/c you are checking that url contains baseUrl :)
you should check UI to assert user is logged in

2021-05-17 12:35 UTC, ivankatsenya commented on client/cypress/fixtures/constants.js
> +  homePageUrlPath: 'http://127.0.0.1:3000/',
this is `baseUrl` - add it to the `cypress.json`

2021-05-17 12:35 UTC, ivankatsenya commented on client/cypress/fixtures/constants.js
> +  homePageUrlPath: 'http://127.0.0.1:3000/',
the only thing is that you should not add `/` from url

2021-05-17 13:39 UTC, s34rching approved these changes
Okay, good to go for now!

2021-05-17 13:39 UTC, s34rching commented on client/cypress/integration/authentication/sign-in.spec.js
> +  function assertUserLogged() {
`assertUserLoggedIn`

2021-05-17 13:47 UTC, merged