Update sign-in.spec file. Add cycle for iterate tests
vitali-akulau/react-app pull request #3
Opened 2021-05-26 09:12 UTC by vitali-akulau

- Update sign-in.spec.js file. Add cycle for iterate of tests
- Add test data

2021-05-26 10:31 UTC, s34rching requested changes
Lets talk about it

2021-05-26 10:31 UTC, s34rching commented on client/cypress/integration/authentication/sign-in.spec.js
> +      it('wrong email | empty email | wrong password | empty password | unregistered user', () => {
nope

2021-05-26 10:31 UTC, s34rching commented on client/cypress/integration/authentication/sign-in.spec.js
> +      it('wrong email | empty email | wrong password | empty password | unregistered user', () => {
iterate over test

2021-06-25 13:41 UTC, s34rching requested changes

2021-06-25 13:41 UTC, s34rching commented on client/cypress/fixtures/users.json
> +  ],
since there is the only `user` object then no need to wrap it up with array

2021-06-25 13:41 UTC, s34rching commented on client/cypress/integration/authentication/sign-in.spec.js
> +        HomePage.clickSignOutLink();
this test depends on the previous one - the worst case you could do
dependent tests - E V I L

2021-06-25 13:41 UTC, s34rching commented on client/cypress/integration/authentication/sign-in.spec.js
> +          `test.user@test${Date.now('YYYY-MM-DDTHH:mm:ss'.replace(':', '-'))}.com`,
looks really poor, please rework by adding helper or whatever

2021-06-25 13:41 UTC, s34rching commented on client/cypress/integration/authentication/sign-in.spec.js
> +      users.signUpInvalidUser.forEach((prop) => {
please use descriptive variable names in callbacks

2021-06-28 08:52 UTC, vitali-akulau commented on client/cypress/integration/authentication/sign-in.spec.js
> +        HomePage.clickSignOutLink();
I think these are independent tests. 
'login with valid credentials' - just logs in.
'sign out' - logs in and out.
'sign out' test - is repeating steps from previous test and do addition step.

2021-06-30 06:25 UTC, s34rching requested changes
And please check most popular screen resolutions in 2021 and change Cypress viewport to that resolution

2021-06-30 06:25 UTC, s34rching commented on client/cypress/integration/authentication/sign-in.spec.js
> +const DATE_FORMAT = 'YYYY-MM-DDTHH:mm:ss';
to be honest you don't need this thing here because `Date.now()` gives you unique part of your email - unix timestamp

2021-06-30 06:25 UTC, s34rching commented on client/cypress/integration/authentication/sign-in.spec.js
> +  `${emailAddress}${Date.now(DATE_FORMAT.replace(':', '-'))}.com`
emails don't look realistic despite test is passing, please rework this util function to return something like `test321654654@test.com`

no need to use args and pass any email, you can just hard-code some part

2021-06-30 06:25 UTC, s34rching commented on client/cypress/integration/authentication/sign-in.spec.js
> +const setEmail = (emailAddress) => (
create helpers module somewhere and move this function to this module

2021-06-30 06:25 UTC, s34rching commented on client/cypress/fixtures/users.json
> +  "signInInvalidUser": [
since this is array please change its name to reflect this is array

2021-06-30 06:25 UTC, s34rching commented on client/cypress/fixtures/users.json
> +  "signUpInvalidUser": [
since this is array please change its name to reflect this is array

2021-06-30 06:25 UTC, s34rching commented on client/cypress/integration/authentication/sign-in.spec.js
> +      users.signInInvalidUser.forEach((prop) => {
you iterate over array, but its name sounds singular

2021-07-19 07:40 UTC, merged